### ISSUE TITLE
Question regarding gamepass

### ISSUE THREAD

**Issue by i286-1** [suluknumoh/TranslateCS2#10]
As far as I know, the game pass files are no longer encyrpted and can freely accessed, at the moment I can access the game files directly from explorer and read/write in the folder without any issues. 

maybe this video can help, just wanted to see if its possible or not

https://github.com/suluknumoh/TranslateCS2/assets/75780057/13a6ee08-3237-4c54-b0c9-11d0d1bf27ee

**Comment by suluknumoh** [comment]
@i286-1 Thank you very much for the information and also for creating and sharing the video 😀

I'm going to add support for XBoxGamePass.

**Comment by i286-1** [comment]
Thank you! I believe the support for accessing game files was added recently so the resources online might not be updated. I am glad that I was able to help you!

**Comment by suluknumoh** [comment]
This issue gets closed, since it should/seem to be fixed.
