### ISSUE TITLE
Problem with the dev branch about gamepass implementation

### ISSUE THREAD

**Issue by i286-1** [suluknumoh/TranslateCS2#14]
I compiled the dev version from the last pull request and found a problem with game pass support. Basically any file from game pass version except cities2.exe can be opened by other apps but cities2.exe can't be opened with an error saying "You don't have permission to open this file.". I suggest you choosing another file for manual selection/selecting the cities2_data folder instead because cities2.exe has some sort of special protection while other files can be freely accessed by other apps.

To see if this was confined to translation app, I tried opening the cities2.exe from HxD and I got a similar result which said "You don't have permission to open this file" while none of the other files I tested caused problems and they were easy accessable.

I tested opening the cities2_data folder with vlc and it had no problems about permissions.

I hope this will helpful!

**Comment by suluknumoh** [comment]
thank you for testing and for your feedback.
im going to change it

**Comment by suluknumoh** [comment]
This issue gets closed, since it should/seem to be fixed.
