### ISSUE TITLE
Mod refuses to work after the 1.1.5f1 and 2.0.4.0 update

### ISSUE THREAD

**Issue by i286-1** [suluknumoh/TranslateCS2#17]
Mod seemingly disappeared, doesnt appear under languages tab or the mod settings place, i confirmed that the mod is installed and its being loaded into the game from logs. Nevertheless I will be adding all the logs and the translation json i used under this post.
[logs.zip](https://github.com/user-attachments/files/15973872/logs.zip)

**Comment by suluknumoh** [comment]
Hey @i286-1 ,
thank you for reporting and for sharing your logs.

After investigating and double checking with all the mods i could gather from the logs.zip,

to me it seems
`Cities2_Data\StreamingAssets\Data~` directory

contains two
`.loc`-files

that internally contain the locale-id 'en-US'.

Did you create and overwrite an existing `.loc`-file?

If you did so:
Please backup that file or those files somewhere.

Within steam there is an option to "verify integrity of game files"
I do not know much about Microsoft XboxGames/Store-Games.

But I found the following that seems to be something similar:
[https://dovetailgames.freshdesk.com/support/solutions/articles/80001018591-how-to-update-microsoft-gaming-services-and-verify-your-game-files](https://dovetailgames.freshdesk.com/support/solutions/articles/80001018591-how-to-update-microsoft-gaming-services-and-verify-your-game-files)

Please try to verify and repair your game files.

**Comment by i286-1** [comment]
I verified the files but the problem still persists. I also manually controlled all the loc files and they were all fine as well. Here is the mod log after all of these
[TranslateCS2.Mod.log](https://github.com/user-attachments/files/15979295/TranslateCS2.Mod.log)

**Comment by suluknumoh** [comment]
OK.
I'm going to release a fix for it within the next couple of minutes.

**Comment by suluknumoh** [comment]
Does it work now?

**Comment by i286-1** [comment]
It seems that the issue is fixed now! Thank you for your quick response!

**Comment by suluknumoh** [comment]
You're very welcome. 😀
